<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <!-- Build info -->
    <TargetFramework>net9.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <OutputType>Exe</OutputType>
    <RuntimeIdentifier>linux-x64</RuntimeIdentifier>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <CheckForOverflowUnderflow>true</CheckForOverflowUnderflow>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <AnalysisMode>Recommended</AnalysisMode>
    <RuntimeIdentifier Condition="$([MSBuild]::IsOSPlatform('Linux'))">linux-x64</RuntimeIdentifier>

    <!-- Assembly info -->
    <VersionPrefix>0.0.1</VersionPrefix>
    <VersionSuffix>$(SourceRevisionId)</VersionSuffix>
    <Authors>Nickolas Gupton</Authors>
    <RepositoryUrl>https://github.com/CorruptComputer/Beepsky</RepositoryUrl>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <SatelliteResourceLanguages>en-US</SatelliteResourceLanguages>
    <SourceControlInformationFeatureSupported>true</SourceControlInformationFeatureSupported>
    <SourceRevisionId>develop</SourceRevisionId>
    <NoDefaultLaunchSettingsFile>True</NoDefaultLaunchSettingsFile>
    <ContinuousIntegrationBuild Condition="'$(GITHUB_ACTIONS)' == 'true'">true</ContinuousIntegrationBuild>
    <InstallService Condition="$(Configuration) == 'Release'">true</InstallService>
  </PropertyGroup>

  <!-- If building in release mode, replace the SourceRevisionId with the 8 character git commit hash -->
  <Target Condition="$(Configuration) == 'Release'" Name="SetSourceRevisionId" BeforeTargets="InitializeSourceControlInformation">
    <Exec Command="git describe --long --always --dirty --exclude=* --abbrev=8" ConsoleToMSBuild="True" IgnoreExitCode="False">
      <Output PropertyName="SourceRevisionId" TaskParameter="ConsoleOutput" />
    </Exec>
  </Target>

  <ItemGroup>
    <PackageReference Include="Autofac" Version="9.0.0" />
    <PackageReference Include="Autofac.Extensions.DependencyInjection" Version="10.0.0" />
    <PackageReference Include="libsodium" Version="1.0.20.1" />
    <PackageReference Include="LLamaSharp" Version="0.25.0" />
    <PackageReference Include="LLamaSharp.Backend.Vulkan" Version="0.25.0" />
    <PackageReference Include="NetCord" Version="1.0.0-alpha.450" />
    <PackageReference Include="NetCord.Hosting" Version="1.0.0-alpha.450" />
    <PackageReference Include="NetCord.Hosting.Services" Version="1.0.0-alpha.450" />
    <PackageReference Include="NetCord.Services" Version="1.0.0-alpha.450" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.11">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.11">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.11" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="9.0.11" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.11" />
    <PackageReference Include="Npgsql" Version="9.0.4" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.4" />
    <PackageReference Update="Packaging.Targets">
        <Version>0.1.232</Version>
    </PackageReference>
    <PackageReference Include="Questy" Version="0.0.5" />
    <PackageReference Include="Questy.Autofac" Version="0.0.4" />
    <PackageReference Include="Serilog" Version="4.3.0" />
    <PackageReference Include="Serilog.Extensions.Hosting" Version="9.0.0" />
    <PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />
  </ItemGroup>

  <ItemGroup>
    <!-- I use Arch BTW, so this is the file path for me when doing local dev, if its different for you cool you can change it -->
    <Content Include="/usr/lib/libopus.so" CopyToOutputDirectory="PreserveNewest" Condition="$(ContinuousIntegrationBuild) != true" />

    <!-- GitHub CI is on Ubuntu: https://packages.ubuntu.com/questing/amd64/libopus-dev/filelist -->
    <Content Include="/usr/lib/x86_64-linux-gnu/libopus.so" CopyToOutputDirectory="PreserveNewest" Condition="$(ContinuousIntegrationBuild) == true" />
  </ItemGroup>

  <ItemGroup Condition="$(Configuration) == 'Release'">
    <!-- Causes the config to get nuked every time the package is installed -->
    <!--Content Include="config.json" CopyToPublishDirectory="PreserveNewest" LinuxFileMode="0640" LinuxPath="/etc/beepsky/config.json" /-->
    <Content Include="beepsky.service" CopyToPublishDirectory="PreserveNewest" LinuxFileMode="0755" LinuxPath="/etc/systemd/system/beepsky.service" />
  </ItemGroup>
</Project>
