<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <!-- Build info -->
    <OutputType>Exe</OutputType>
    <RuntimeIdentifier>linux-x64</RuntimeIdentifier>

    <!-- Assembly info -->
    <NoDefaultLaunchSettingsFile>True</NoDefaultLaunchSettingsFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="libsodium" Version="1.0.21" />
    <PackageReference Include="NetCord" Version="1.0.0-alpha.477" />
    <PackageReference Include="NetCord.Hosting" Version="1.0.0-alpha.477" />
    <PackageReference Include="NetCord.Hosting.Services" Version="1.0.0-alpha.476" />
    <PackageReference Include="NetCord.Services" Version="1.0.0-alpha.476" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.5">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <!-- Native binaries required by NetCord for Voice to work: https://github.com/NetCordDev/NetCord/blob/alpha/Documentation/guides/basic-concepts/installing-native-dependencies.md -->
  <ItemGroup>
    <!-- v1.1.1 from: https://github.com/discord/libdave/releases -->
    <Content Include="./libdave.so" CopyToOutputDirectory="PreserveNewest" />

    <!-- I use Arch BTW, so this is the file path for me when doing local dev, if its different for you cool you can change it -->
    <Content Include="/usr/lib/libopus.so" CopyToOutputDirectory="PreserveNewest" Condition="$(ContinuousIntegrationBuild) != true" />

    <!-- GitHub CI is on Ubuntu: https://packages.ubuntu.com/questing/amd64/libopus-dev/filelist -->
    <Content Include="/usr/lib/x86_64-linux-gnu/libopus.so" CopyToOutputDirectory="PreserveNewest" Condition="$(ContinuousIntegrationBuild) == true" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../Beepsky.Core/Beepsky.Core.csproj" />
  </ItemGroup>
</Project>
