name: setup-env
description: Setup Environment

runs:
  using: composite
  steps:
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Install libopus-dev
      shell: bash
      run: |
        sudo apt-get install -y libopus-dev

    - name: Print .NET version and SDKs
      shell: bash
      run: |
        dotnet --version
        dotnet --list-sdks

    - name: Restore Tools
      shell: bash
      run: |
        cd Beepsky
        dotnet tool restore
        cd ..