using NetCord.Gateway;

namespace Beepsky.Features.Chatty.Normal;

/// <inheritdoc />
public sealed class TellSkeletonHeSmells : IRequestHandler<TellSkeletonHeSmells.Command, CommandResponse>
{
    /// <summary>
    ///   Tell Skeleton to go back to the warhammer channel
    /// </summary>
    /// <param name="Message"></param>
    public record Command(Message Message) : IRequest<CommandResponse>;

    /// <inheritdoc />
    public async Task<CommandResponse> Handle(Command request, CancellationToken cancellationToken)
    {
        string response = possibleResponses[rdm.Next(possibleResponses.Count)];

        await request.Message.ReplyAsync(response, cancellationToken: cancellationToken);

        return CommandResponse.Pass();
    }

    private static readonly Random rdm = new();

    private readonly List<string> possibleResponses =
    [
        "CRIMINAL ENTITY DETECTED. WARHAMMER-CLASS ACTIVITY OUTSIDE AUTHORIZED ZONE. RETURN TO <#819648286209343488> OR BE CHARGED WITH CODE 47-C: LORE DUMPING WITHOUT PERMIT.",
        "ILLEGAL TABLETOP MONOLOGUE IDENTIFIED. YOU ARE OUTSIDE YOUR DESIGNATED CONTAINMENT AREA. PROCEED TO <#819648286209343488> IMMEDIATELY. VIOLATION: SECTION 22-A: MINIATURE-INDUCED PUBLIC NUISANCE.",
        "YOUR WARHAMMER OUTPUT IS UNAUTHORIZED IN THIS SECTOR. RELOCATE TO <#819648286209343488> OR FACE SUBJUGATION UNDER STATUTE 09-F: HERESY OF EXCESSIVE FANDOM.",
        "STOP. YOU ARE EMITTING WARHAMMER LORE OUTSIDE THE APPROVED CHANNEL. RETURN TO <#819648286209343488>. CURRENT OFFENSE: FELONY 31-K: UNAUTHORIZED LORE RECITATION.",
        "UNSANCTIONED IMPERIUM DISCUSSION DETECTED. CORRECT YOUR COURSE TO <#819648286209343488> AT ONCE. YOU ARE IN BREACH OF ORDINANCE 88-D: CRIMINAL OVEREXPLANATION OF THE IMPERIUM.",
        "UNAUTHORIZED WARHAMMER TRANSMISSION DETECTED. PROCEED TO <#819648286209343488> OR FACE CHARGES UNDER CODE 51-A: OUT-OF-BOUNDS LORE BROADCASTING.",
        "VIOLATION CONFIRMED: TABLETOP CONTENT EMITTED IN A NON-DESIGNATED ZONE. RELOCATE TO <#819648286209343488>. OFFENSE: REGULATION 14-D: MISPLACED IMPERIUM DISCOURSE.",
        "HALT. IMPERIAL MINIATURE ANALYSIS IS NOT AUTHORIZED HERE. RETURN TO <#819648286209343488> IMMEDIATELY. CLASSIFICATION: INFRACTION 70-C: STRATEGIC OVERCOMMENTARY.",
        "SUSPECTED LORE DUMP DETECTED OUTSIDE PERMITTED CHANNELS. REASSIGN YOURSELF TO <#819648286209343488>. CURRENT CITATION: SECTION 23-F: UNCONTAINED WARHAMMER RHETORIC.",
        "CEASE UNAPPROVED WARHAMMER DISCUSSION. MIGRATE TO <#819648286209343488> WITHOUT DELAY. BREACH: STATUTE 05-E: TACTICAL EXPOSITION IN A RESTRICTED SECTOR.",
        "WARNING: WARHAMMER CONTENT LEAK OCCURRING BEYOND ITS QUARANTINE CHANNEL. REPORT TO <#819648286209343488>. CHARGE: CLAUSE 89-K: IMPROPER DEPLOYMENT OF IMPERIUM LORE.",
        "OUT-OF-CHANNEL LORE ACTIVITY DETECTED. MOVE TO <#819648286209343488> AT ONCE. YOU ARE IN CONTRAVENTION OF ORDER 33-H: MINIATURE WARFARE COMMENTARY OUTSIDE BOUNDARY.",
        "UNSANCTIONED STRATEGY DISCUSSION OCCURRING. RELOCATE TO <#819648286209343488> OR FACE PENALTIES UNDER PROTOCOL 12-M: EXCESSIVE TABLETOP THEMATICS.",
        "ALERT: IMPERIUM-RELATED SPEECH IN A NON-AUTHORIZED AREA. IMMEDIATE TRANSFER TO <#819648286209343488> REQUIRED. OFFENSE: RULE 40-J: LORE MIGRATION FAILURE.",
        "TERMINATE YOUR CURRENT LINE OF WARHAMMER OUTPUT. THIS LOCATION IS NOT CLEARED. MOVE TO <#819648286209343488>. VIOLATION: REGISTRY ENTRY 66-P: STRATEGIC COMMENTARY MISALLOCATION."
    ];
}