// <auto-generated />
using System;
using Beepsky.Core.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Beepsky.Core.Database.Migrations
{
    [DbContext(typeof(BeepskyDbContext))]
    [Migration("20260227235237_AudioDownloadTable")]
    partial class AudioDownloadTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Beepsky.Database.DbSets.AudioDownload", b =>
                {
                    b.Property<Guid>("DownloadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DownloadUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("LastAccessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PlayCount")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("DownloadId");

                    b.ToTable("AudioDownloads");
                });

            modelBuilder.Entity("Beepsky.Database.DbSets.DiscordGuild", b =>
                {
                    b.Property<decimal>("GuildId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("GuildId");

                    b.ToTable("DiscordGuilds");
                });

            modelBuilder.Entity("Beepsky.Database.DbSets.DiscordGuildUserStatistic", b =>
                {
                    b.Property<Guid>("DiscordGuildUserStatisticId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("BeepskyChattedWith")
                        .HasColumnType("bigint");

                    b.Property<long>("BeepskyCommandsUsed")
                        .HasColumnType("bigint");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<long>("MessagesDeletedBy")
                        .HasColumnType("bigint");

                    b.Property<long>("MessagesDeletedFrom")
                        .HasColumnType("bigint");

                    b.Property<long>("MessagesSent")
                        .HasColumnType("bigint");

                    b.Property<long>("MessagesSentOnMostChattyDay")
                        .HasColumnType("bigint");

                    b.Property<long>("MessagesSentToday")
                        .HasColumnType("bigint");

                    b.Property<DateOnly>("MostChattyDay")
                        .HasColumnType("date");

                    b.Property<long>("TimesJoinedVoice")
                        .HasColumnType("bigint");

                    b.Property<long>("TimesKickedFromVoice")
                        .HasColumnType("bigint");

                    b.Property<DateOnly>("Today")
                        .HasColumnType("date");

                    b.Property<decimal>("UserId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("DiscordGuildUserStatisticId");

                    b.HasIndex("GuildId");

                    b.HasIndex("UserId");

                    b.HasIndex("Year");

                    b.ToTable("DiscordGuildUserStatistics");
                });

            modelBuilder.Entity("Beepsky.Database.DbSets.DiscordUser", b =>
                {
                    b.Property<decimal>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(20,0)");

                    b.Property<bool>("CanUseCommands")
                        .HasColumnType("boolean");

                    b.Property<string>("Mention")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.ToTable("DiscordUsers");
                });

            modelBuilder.Entity("Beepsky.Database.DbSets.DiscordGuildUserStatistic", b =>
                {
                    b.HasOne("Beepsky.Database.DbSets.DiscordGuild", null)
                        .WithMany()
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Beepsky.Database.DbSets.DiscordUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
